"""TDS Driver Foundation namespace.

v3.1.20 extends the driver foundation for the future native
Driver VM, Builder, Registry and Studio. These helpers preserve authority boundaries while modeling trust states, manifests, signatures and
trace ranking plus strict non-executing TDDL parsing/validation, deterministic bytecode packaging, VM contract audits, a non-executing VM skeleton, the deterministic runtime execution path, a non-halting DriverVMResult envelope, AI-safe DriverFoundry API, Runtime Manager execution evidence, deterministic fixture regression harnessing, an admin batch review layer, read-only evidence bundle/audit trail export, bounded Studio admin review action submission, an optional PyQt5 cockpit shell, a manual Studio proposal builder routed through Foundry, live panel runtime coordination, review workflow, evidence timeline, risk intelligence, an opt-in Driver VM performance evidence harness, the Driver Studio Manual Builder UI Runtime, and export/audit packet preparation surfaces.
"""

from .manifest import DriverManifest, DriverSafety, validate_manifest
from .registry import DriverRegistry, DriverRecord, DriverState, RegistryError
from .signature import SignaturePolicy, SignatureVerdict, sign_payload, verify_signature
from .trace import TraceEvidence, rank_traces
from .audit import VMInstructionContract, audit_vm_contract, vm_contract_table
from .vm import DriverVMContext, DriverVMResult, DriverVMRuntime, DriverVMSkeleton, VMExecutionResult, VMFault, VMLoadedPackage, VMState, VMStatus

from .foundry import (
    DriverFoundry,
    DriverFoundryContext,
    DriverFoundryPolicy,
    DriverFoundryResult,
    FoundryFault,
    FoundryStage,
    FoundryStatus,
    foundry_capability_matrix,
)


from .performance import (
    DriverVMPerformanceBackend,
    DriverVMPerformanceComparison,
    DriverVMPerformanceHarness,
    DriverVMPerformancePolicy,
    DriverVMPerformanceReport,
    DriverVMPerformanceRun,
    DriverVMPerformanceStatus,
    DriverVMPerformanceSummary,
    driver_vm_performance_capability_matrix,
    driver_vm_performance_enabled,
)

from .runtime_manager import (
    DriverExecutionEvidence,
    DriverRuntimeManager,
    RuntimeManagerFault,
    RuntimeManagerPolicy,
    RuntimeManagerStatus,
    runtime_manager_capability_matrix,
)

from .regression import (
    DriverFixtureCase,
    DriverRegressionHarness,
    DriverRegressionReport,
    DriverRegressionResult,
    RegressionMismatch,
    RegressionStatus,
    regression_harness_capability_matrix,
    runtime_fixture_hash,
)


from .evidence import (
    AuditTrailStatus,
    DriverAuditEvent,
    DriverAuditEventType,
    DriverAuditTrail,
    DriverEvidenceBundle,
    DriverEvidenceRecord,
    EvidenceBundleExporter,
    EvidenceBundleManifest,
    EvidenceBundleStatus,
    EvidenceExportFormat,
    EvidenceIntegrityStatus,
    evidence_export_capability_matrix,
)

from .review import (
    BatchReviewPolicy,
    BatchReviewStatus,
    DriverBatchReviewBoard,
    DriverBatchReviewReport,
    DriverReviewDecision,
    DriverReviewItem,
    ReviewAction,
    ReviewDecisionStatus,
    ReviewFault,
    batch_review_capability_matrix,
)

from .studio import (
    DriverStudioConsoleSnapshot,
    DriverStudioEventRow,
    DriverStudioPanelSnapshot,
    DriverStudioQuickTestReport,
    DriverStudioQueueItem,
    DriverStudioReadOnlyConsole,
    DriverStudioRiskCard,
    DriverStudioSession,
    StudioConsoleStatus,
    StudioGate,
    StudioGateResult,
    StudioPanelKind,
    StudioPanelStatus,
    run_studio_quick_test,
    studio_instruction_reference,
    studio_readonly_capability_matrix,
)

from .studio_builder import (
    DriverStudioManualProposalBuilder,
    StudioManualDriverTask,
    StudioManualProposalPreview,
    StudioManualProposalReport,
    StudioManualProposalStatus,
    studio_manual_builder_capability_matrix,
)

from .studio_actions import (
    DriverStudioAdminReviewActions,
    StudioReviewActionDecision,
    StudioReviewActionEvent,
    StudioReviewActionRequest,
    StudioReviewActionStatus,
    StudioReviewSubmissionPolicy,
    StudioReviewSubmissionReport,
    StudioReviewSubmissionStatus,
    studio_admin_review_capability_matrix,
)

from .bytecode import (
    BYTECODE_MAGIC,
    BYTECODE_VERSION,
    BytecodeInstruction,
    BytecodeOpcode,
    BytecodePackage,
    compile_program,
    compile_tddl,
    decompile_to_ir,
    opcode_table,
    validate_bytecode_package,
)
from .tddl import (
    InstructionName,
    TDDLInstruction,
    TDDLProgram,
    TDDLValidationError,
    instruction_specs,
    parse_tddl,
    validate_tddl,
)

__all__ = [
    "DriverManifest",
    "DriverSafety",
    "validate_manifest",
    "DriverRegistry",
    "DriverRecord",
    "DriverState",
    "RegistryError",
    "SignaturePolicy",
    "SignatureVerdict",
    "sign_payload",
    "verify_signature",
    "TraceEvidence",
    "rank_traces",
    "VMInstructionContract",
    "audit_vm_contract",
    "vm_contract_table",
    "DriverVMContext",
    "DriverVMResult",
    "DriverVMRuntime",
    "DriverVMSkeleton",
    "VMExecutionResult",
    "VMFault",
    "VMLoadedPackage",
    "VMState",
    "VMStatus",
    "InstructionName",
    "TDDLInstruction",
    "TDDLProgram",
    "TDDLValidationError",
    "instruction_specs",
    "parse_tddl",
    "validate_tddl",
    "BYTECODE_MAGIC",
    "BYTECODE_VERSION",
    "BytecodeInstruction",
    "BytecodeOpcode",
    "BytecodePackage",
    "compile_program",
    "compile_tddl",
    "decompile_to_ir",
    "opcode_table",
    "validate_bytecode_package",
    "DriverStudioConsoleSnapshot",
    "DriverStudioEventRow",
    "DriverStudioPanelSnapshot",
    "DriverStudioQuickTestReport",
    "DriverStudioQueueItem",
    "DriverStudioReadOnlyConsole",
    "DriverStudioRiskCard",
    "DriverStudioSession",
    "StudioConsoleStatus",
    "StudioGate",
    "StudioGateResult",
    "StudioPanelKind",
    "StudioPanelStatus",
    "run_studio_quick_test",
    "studio_instruction_reference",
    "studio_readonly_capability_matrix",
    "DriverStudioManualProposalBuilder",
    "StudioManualDriverTask",
    "StudioManualProposalPreview",
    "StudioManualProposalReport",
    "StudioManualProposalStatus",
    "studio_manual_builder_capability_matrix",
    "DriverStudioAdminReviewActions",
    "StudioReviewActionDecision",
    "StudioReviewActionEvent",
    "StudioReviewActionRequest",
    "StudioReviewActionStatus",
    "StudioReviewSubmissionPolicy",
    "StudioReviewSubmissionReport",
    "StudioReviewSubmissionStatus",
    "studio_admin_review_capability_matrix",
    "DriverFoundry",
    "DriverFoundryContext",
    "DriverFoundryPolicy",
    "DriverFoundryResult",
    "FoundryFault",
    "FoundryStage",
    "FoundryStatus",
    "foundry_capability_matrix",
    "DriverExecutionEvidence",
    "DriverRuntimeManager",
    "RuntimeManagerFault",
    "RuntimeManagerPolicy",
    "RuntimeManagerStatus",
    "DriverVMPerformanceBackend",
    "DriverVMPerformanceComparison",
    "DriverVMPerformanceHarness",
    "DriverVMPerformancePolicy",
    "DriverVMPerformanceReport",
    "DriverVMPerformanceRun",
    "DriverVMPerformanceStatus",
    "DriverVMPerformanceSummary",
    "driver_vm_performance_capability_matrix",
    "driver_vm_performance_enabled",
    "runtime_manager_capability_matrix",
    "DriverFixtureCase",
    "DriverRegressionHarness",
    "DriverRegressionReport",
    "DriverRegressionResult",
    "RegressionMismatch",
    "RegressionStatus",
    "regression_harness_capability_matrix",
    "runtime_fixture_hash",
    "AuditTrailStatus",
    "DriverAuditEvent",
    "DriverAuditEventType",
    "DriverAuditTrail",
    "DriverEvidenceBundle",
    "DriverEvidenceRecord",
    "EvidenceBundleExporter",
    "EvidenceBundleManifest",
    "EvidenceBundleStatus",
    "EvidenceExportFormat",
    "EvidenceIntegrityStatus",
    "evidence_export_capability_matrix",
    "BatchReviewPolicy",
    "BatchReviewStatus",
    "DriverBatchReviewBoard",
    "DriverBatchReviewReport",
    "DriverReviewDecision",
    "DriverReviewItem",
    "ReviewAction",
    "ReviewDecisionStatus",
    "ReviewFault",
    "batch_review_capability_matrix",
]
